;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_tgi_clear
	.import		_tgi_setpalette
	.import		_tgi_ioctl
	.export		_title_init
	.import		_current_game_part
	.import		_joy
	.import		_clear_screen
	.import		_root_sprptr
	.import		_refresh_screen
	.import		_joy_masks
	.import		_joy_read
	.import		_titre_pal
	.import		_titre_spr
	.export		_sprite_root

.segment	"TITLE_DATA"

_sprite_root:
	.byte	$C4
	.byte	$10
	.byte	$20
	.word	$0000
	.addr	_titre_spr
	.word	$0000
	.word	$0000
	.word	$0100
	.word	$0100
	.byte	$01
	.byte	$23
	.byte	$45
	.byte	$67
	.byte	$89
	.byte	$AB
	.byte	$CD
	.byte	$EF

; ---------------------------------------------------------------
; void __near__ title_init (void)
; ---------------------------------------------------------------

.segment	"TITLE_CODE"

.proc	_title_init: near

.segment	"TITLE_CODE"

	ldx     #$00
	lda     #$01
	sta     _current_game_part
	lda     #<(_sprite_root)
	ldx     #>(_sprite_root)
	sta     _root_sprptr
	stx     _root_sprptr+1
	ldx     #$00
	lda     #$00
	sta     _clear_screen
	jmp     L0036
L0036:	lda     #$04
	jsr     pusha
	ldx     #$00
	lda     #$00
	jsr     _tgi_ioctl
	stx     tmp1
	ora     tmp1
	jne     L0036
	jsr     _tgi_clear
	lda     #<(_titre_pal)
	ldx     #>(_titre_pal)
	jsr     _tgi_setpalette
	jmp     L003F
L003D:	lda     #$00
	jsr     _joy_read
	sta     _joy
	ldx     #$00
	lda     _joy
	jsr     pushax
	ldx     #$00
	lda     _joy_masks+4
	jsr     tosandax
	stx     tmp1
	ora     tmp1
	jne     L0045
	ldx     #$00
	lda     _joy
	jsr     pushax
	ldx     #$00
	lda     _joy_masks+5
	jsr     tosandax
	stx     tmp1
	ora     tmp1
	jne     L0045
	ldx     #$00
	lda     #$00
	jeq     L004C
L0045:	ldx     #$00
	lda     #$01
L004C:	jeq     L0044
	jmp     L003E
L0044:	ldy     #$00
	jsr     _refresh_screen
L003F:	jmp     L003D
L003E:	ldx     #$00
	lda     #$02
	sta     _current_game_part
	rts

.endproc

